# Generated by Django 4.2.3 on 2023-07-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="chat_data",
            new_name="ChatData",
        ),
        migrations.RenameModel(
            old_name="relation",
            new_name="FriendRequest",
        ),
        migrations.RenameModel(
            old_name="record",
            new_name="MessageTracker",
        ),
        migrations.RenameModel(
            old_name="user_data",
            new_name="UserData",
        ),
    ]
